import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../../styles/Game.module.scss'
import Canvas, {PaintCoords} from "../../components/canvas";
import { io, Socket } from 'socket.io-client';
import {useEffect, useRef} from "react";

const Home: NextPage = () => {
    const socketRef = useRef<Socket>();
    const canvasCtxRef = useRef<CanvasRenderingContext2D>();

    useEffect(() => {
        if (typeof window !== 'undefined') {
            socketRef.current = io('http://localhost:4000');

            socketRef.current?.on('clear_canvas', () => {
                if (canvasCtxRef.current) {
                    canvasCtxRef.current?.clearRect(0, 0, 1000, 600);
                }
            })

            socketRef.current.on('repaint', ({ x, y, dx, dy }) => {
                if (canvasCtxRef.current) {
                    canvasCtxRef.current.beginPath
                    canvasCtxRef.current.moveTo(x, y);
                    canvasCtxRef.current.lineTo(x - dx, y - dy);
                    canvasCtxRef.current.stroke();
                    canvasCtxRef.current.closePath();
                }
            })
        }
    }, [])

    const onPaint = (data: PaintCoords) => {
        if (socketRef.current) {
            socketRef.current.emit('paint', data);
        }
    }

    const onClear = () => {
        if (socketRef.current) {
            socketRef.current.emit('clear');
        }
    }

    return (
        <div>
            <Head>
                <title>Игра</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={styles.game}>
                <div className={styles.chat}>
                    <h2 className={styles.chatTitle}>Чат</h2>
                    <div className={styles.chatMessage}>
                        <div className={styles.chatItem}>
                            <p className={styles.messageOwner}>Vasya</p>
                            <p>Hello World</p>
                        </div>
                    </div>
                    <div className={styles.chatInput}>
                        <input type="text"/>
                        <button>Send</button>
                    </div>
                </div>

                <div className={styles.canvas}>
                    <Canvas onClear={onClear} onPaint={onPaint} onInit={canvasCtx => canvasCtxRef.current = canvasCtx} />
                </div>
            </div>
        </div>
    )
}

export default Home
