import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>CROCODILE GAME</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={styles.container}>
                <h1 className={styles.title}>CROCODILE</h1>
                <p className={styles.text}>Сыграй в крокодила с друзьями</p>
                <p className={styles.text}>Догадаются ли они что ты думаешь?</p>
                <button className={styles.startGameButton}>Создать игру</button>
            </div>
        </div>
    )
}

export default Home
